export const GAME_DATA = [
  {
    devName: "Saurav Kumar",
    games: [
      {
        title: "PIG GAME",
        shortDescription:
          "Players take turns to roll a single die as many times as they wish, adding all roll results to a running total.",
        longDescription: `Pig is a simple dice game first described in print by John Scarne in 1945.
                          Players take turns to roll a single die as many times as they wish, adding
                          all roll results to a running total, but losing their gained score for the
                          turn if they roll a 1. `,
        link: "games/pig_game/index.html",
        image: "assets/gameImages/pig-game.png",
        profilePic: "assets/devImages/profilePic.png",
      },
      {
        title: "GUESS MY NUMBER",
        shortDescription:
          "The game is to guess a random number generated by computer in range 1 – 20 in minimum number of Guesses.",
        longDescription: `This JavaScript number guessing game project's objective is to code a game
                          where the user must guess a randomly generated number from 1 to 20.`,
        link: "games/guess_my_number/index.html",
        image: "assets/gameImages/guess-my-number.png",
        profilePic: "assets/devImages/profilePic.png",
      },
    ],
    profilePic: "assets/devImages/profilePic.png",
    aboutPic: "assets/devImages/aboutPic.png",
    about: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
            industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type
            and scrambled it to make a type specimen book.
            Lorem Ipsum is simply dummy text of the printing and typesetting industry.`,
    gitLink: "#",
    linkedinLink: "#",
  },
  {
    devName: "Rishy Prashar",
    games: [
      {
        title: "SNAKE GAME",
        shortDescription:
          "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        longDescription: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
            industry's standard dummy text ever since the 1500s,`,
        link: "games/snake_game/index.html",
        image: "assets/gameImages/snake-game.png",
        profilePic: "assets/devImages/profilePic.png",
      },
    ],
    profilePic: "assets/devImages/profilePic.png",
    aboutPic: "assets/devImages/aboutPic.png",
    about: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
            industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type
            and scrambled it to make a type specimen book.
            Lorem Ipsum is simply dummy text of the printing and typesetting industry.`,
    gitLink: "#",
    linkedinLink: "#",
  },
  {
    devName: "Anurag Nayak",
    games: [
      {
        title: "TIC TAC TOE",
        shortDescription:
          "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        longDescription: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
            industry's standard dummy text ever since the 1500s,`,
        link: "games/tic_tac_toe/game.html",
        image: "assets/gameImages/tic-tac-toe.png",
        profilePic: "assets/devImages/profilePic.png",
      },
    ],
    profilePic: "assets/devImages/profilePic.png",
    aboutPic: "assets/devImages/aboutPic.png",
    about: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
            industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type
            and scrambled it to make a type specimen book.
            Lorem Ipsum is simply dummy text of the printing and typesetting industry.`,
    gitLink: "#",
    linkedinLink: "#",
  },
  {
    devName: "Bhavaneet Singh",
    games: [
      {
        title: "FALL GAME",
        shortDescription:
          "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        longDescription: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
            industry's standard dummy text ever since the 1500s,`,
        link: "games/fall_game/index.html",
        image: "assets/gameImages/fall-game.png",
        profilePic: "assets/devImages/profilePic.png",
      },
    ],
    profilePic: "assets/devImages/profilePic.png",
    aboutPic: "assets/devImages/aboutPic.png",
    about: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
            industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type
            and scrambled it to make a type specimen book.
            Lorem Ipsum is simply dummy text of the printing and typesetting industry.`,
    gitLink: "#",
    linkedinLink: "#",
  },
  {
    devName: "Aniket Agarwal",
    games: [
      {
        title: "PIG GAME",
        shortDescription:
          "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        longDescription: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
            industry's standard dummy text ever since the 1500s,`,
        link: "#",
        image: "#",
        profilePic: "assets/devImages/profilePic.png",
      },
    ],
    profilePic: "assets/devImages/profilePic.png",
    aboutPic: "assets/devImages/aboutPic.png",
    about: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
            industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type
            and scrambled it to make a type specimen book.
            Lorem Ipsum is simply dummy text of the printing and typesetting industry.`,
    gitLink: "#",
    linkedinLink: "#",
  },
  {
    devName: "Ved Prakash Dubey",
    games: [
      {
        title: "ASTEROIDS",
        shortDescription:
          "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        longDescription: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
            industry's standard dummy text ever since the 1500s,`,
        link: "games/asteroids/asteroids.html",
        image: "assets/gameImages/asteroids.png",
        profilePic: "assets/devImages/profilePic.png",
      },
    ],
    profilePic: "assets/devImages/profilePic.png",
    aboutPic: "assets/devImages/aboutPic.png",
    about: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
            industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type
            and scrambled it to make a type specimen book.
            Lorem Ipsum is simply dummy text of the printing and typesetting industry.`,
    gitLink: "#",
    linkedinLink: "#",
  },
  {
    devName: "Aakash Gupta",
    games: [
      {
        title: "PIG GAME",
        shortDescription:
          "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        longDescription: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
            industry's standard dummy text ever since the 1500s,`,
        link: "#",
        image: "#",
        profilePic: "assets/devImages/profilePic.png",
      },
    ],
    profilePic: "assets/devImages/profilePic.png",
    aboutPic: "assets/devImages/aboutPic.png",
    about: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
            industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type
            and scrambled it to make a type specimen book.
            Lorem Ipsum is simply dummy text of the printing and typesetting industry.`,
    gitLink: "#",
    linkedinLink: "#",
  },
];
